### ISSUE TITLE
Не собирается приложение

### ISSUE THREAD

**Issue by jinsem** [kuznetsovin/egts#1]
Разбираюсь сейчас с протоколом ЕГТС. Нашел статью https://www.swe-notes.ru/post/protocol-egts/ где была опубликована ссылка на этот репозиторий. Пытаюсь собрать это приложение, чтоб посмотреть как обработка протокола работает на практике, но сборка вылетает с ошибкой: 

name@host:~/work/prj/_examples/egts$ go build
go: finding github.com/kuznetsovin/egts.go v0.0.0-20190514121832-d9ba019879f0
go: github.com/kuznetsovin/egts.go@v0.0.0-20190514121832-d9ba019879f0: git fetch -f https://github.com/kuznetsovin/egts.go refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/jin/go/pkg/mod/cache/vcs/f3b9022dab7c54b338798166445ee09c1a1f9944a560327770d7e2d4ada63a58: exit status 128:
	ERROR: Repository not found.
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
go: error loading module requirements

github.com/kuznetsovin/egts.go - это какой то приватный репозиторий? Или в go.mod опечатка в имени репозитория?

**Comment by kuznetsovin** [comment]
Да, в go.mod опечатка в имени репозитория, библиотека для работы с егтс лежит в этом же репозитории в папке pkg

**Comment by kuznetsovin** [comment]
Пофиксил go.mod
